// <auto-generated />
using System;
using BUGS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BUGS.Migrations
{
    [DbContext(typeof(BUGSContext))]
    [Migration("20260809195327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BUGS.Data.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BondType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContractPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustStreetAdd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropStreetAdd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purchaser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RenewalFee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThroughDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TransferFee")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
